# Generated by Django 3.2.9 on 2021-11-21 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrip_str', models.TextField(max_length=500)),
                ('title_str', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=100)),
                ('interest', models.CharField(max_length=100)),
                ('date', models.DateTimeField(verbose_name='date_asked')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_str', models.CharField(max_length=50)),
                ('date', models.DateTimeField(verbose_name='date_asked')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_link', models.URLField()),
                ('descrip_str', models.TextField(max_length=1000)),
                ('title_str', models.CharField(max_length=100)),
                ('date_completed', models.DateTimeField(verbose_name='date_finished')),
                ('image_path', models.CharField(max_length=100)),
                ('skills_used', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.skills')),
            ],
        ),
        migrations.CreateModel(
            name='Eduaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_str', models.CharField(max_length=200)),
                ('major_str', models.CharField(max_length=150)),
                ('expec_grad', models.IntegerField()),
                ('cool_classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.classes')),
            ],
        ),
    ]
