# Generated by Django 3.2.9 on 2022-08-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_project_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_path',
            field=models.URLField(),
        ),
    ]
